development:
  oauth2:            true
  authorization_uri: 'https://developers.sparkplatform.com/oauth2'
  access_uri:        'https://developers.sparkapi.com/v1/oauth2/grant'
  redirect_uri:      'http://localhost/oauth2/callback'
  client_id:         'developmentid124nj4qu3pua'
  client_secret:     'developmentsecret4orkp29f'
  endpoint:          'https://developers.sparkapi.com'
  oauth2_provider:   'SparkApi::TestOAuth2Provider'

test:
  oauth2:            true
  authorization_uri: 'https://developers.sparkplatform.com/oauth2'
  access_uri:        'https://developers.sparkapi.com/v1/oauth2/grant'
  redirect_uri:      'http://localhost/oauth2/callback'
  client_id:         'developmentid124nj4qu3pua'
  client_secret:     'developmentsecret4orkp29f'
  endpoint:          'https://developers.sparkapi.com'
  oauth2_provider:   'SparkApi::TestOAuth2Provider'
  
production:
  oauth2:            true
  authorization_uri: 'https://sparkplatform.com/oauth2'
  access_uri:        'https://api.sparkapi.com/v1/oauth2/grant'
  redirect_uri:      'http://localhost/oauth2/callback'
  client_id:         'production1id124nj4qu3pua'
  client_secret:     'productionsecret4orkp29fv'
  endpoint:          'https://api.sparkapi.com'

