require 'spark_api/models/dirty'
require 'spark_api/models/base'
require 'spark_api/models/constraint'
require 'spark_api/models/finders'
require 'spark_api/models/defaultable'
require 'spark_api/models/subresource'
require 'spark_api/models/concerns'

require 'spark_api/models/account'
require 'spark_api/models/account_report'
require 'spark_api/models/account_roster'
require 'spark_api/models/activity'
require 'spark_api/models/connect_prefs'
require 'spark_api/models/contact'
require 'spark_api/models/comment'
require 'spark_api/models/custom_fields'
require 'spark_api/models/document'
require 'spark_api/models/email_link'
require 'spark_api/models/fields'
require 'spark_api/models/idx'
require 'spark_api/models/idx_link'
require 'spark_api/models/incomplete_listing'
require 'spark_api/models/floplan'
require 'spark_api/models/listing'
require 'spark_api/models/listing_cart'
require 'spark_api/models/listing_meta_translations'
require 'spark_api/models/market_statistics'
require 'spark_api/models/media'
require 'spark_api/models/message'
require 'spark_api/models/news_feed_meta'
require 'spark_api/models/newsfeed'
require 'spark_api/models/note'
require 'spark_api/models/notification'
require 'spark_api/models/open_house'
require 'spark_api/models/photo'
require 'spark_api/models/portal'
require 'spark_api/models/portal_listing_cart'
require 'spark_api/models/property_types'
require 'spark_api/models/rental_calendar'
require 'spark_api/models/rule'
require 'spark_api/models/saved_search'
require 'spark_api/models/search_template/quick_search'
require 'spark_api/models/shared_link'
require 'spark_api/models/shared_listing'
require 'spark_api/models/sort'
require 'spark_api/models/standard_fields'
require 'spark_api/models/system_info'
require 'spark_api/models/system_info_search'
require 'spark_api/models/tour_of_home'
require 'spark_api/models/video'
require 'spark_api/models/virtual_tour'
require 'spark_api/models/vow_account'

module SparkApi
  module Models

  end
end
